### ISSUE TITLE
SAINT problem with prey and bat with same name

### ISSUE THREAD

**Issue by mavino** [bornea/APOSTL#9]
Not sure if this is a SAINT problem or APOSTL.
When bait and preygene name is the same the Spec ms count becomes 0 in every replicate as follows:

![image](https://user-images.githubusercontent.com/22825333/183112880-65784f1b-b475-458d-89c4-a463390027dc.png)

I gave it a fake name as XXX in the prey file and everything went fine:

![image](https://user-images.githubusercontent.com/22825333/183113509-afbf26e1-89a1-43cd-b6f7-b2f29fbdba7d.png)

Thanks a lot.
Mariano

**Comment by brentkuenzi** [comment]
I’m pretty sure that is a SAINT quirk
